### ISSUE TITLE
Неправильно преобразуется даты

### ISSUE THREAD

**Issue by avdosev** [avdosev/habr_app#11]
При преобразовании даты в читабельный текст если месяцы не равны то не высветился "вчера в ..."

**Comment by Sapfir0** [comment]
Непонятненько

**Comment by we2seek** [comment]
Мой шар оракула подсказывает, что автор говорит, например, что если предположить, что сегодня 1 ноября, то дата 31 октября не пишется, как "вчера"

**Comment by avdosev** [comment]
Да, в этом и заключается проблема, ваш шар оракула прав
