### ISSUE TITLE
Возможность открывать произвольные статьи

### ISSUE THREAD

**Issue by tankistqazwsx** [avdosev/habr_app#2]
Нужна возможность открывать произвольные статьи — для упрощения тестирования и просто как удобная фича.

**Comment by unterumarmung** [comment]
Что такое - произвольная статья?

**Comment by Sapfir0** [comment]
Не последние опубликованные статьи, а те, которые я хочу

**Comment by avdosev** [comment]
@Sapfir0 , а какие ты хочешь?

**Comment by unterumarmung** [comment]
Я хочу все

**Comment by Sapfir0** [comment]
> @Sapfir0 , а какие ты хочешь?

Свою статейку хочу прочитать

**Comment by avdosev** [comment]
Тоесть ты хочешь поиск статей?

**Comment by Sapfir0** [comment]
**Да.**

**Comment by avdosev** [comment]
Отлично. Я сделал. Будет в следующем релизе
