### ISSUE TITLE
Null in some positions

### ISSUE THREAD

**Issue by istudyatuni** [avdosev/habr_app#23]
Кажется API опять изменилось
![31722.png](https://user-images.githubusercontent.com/43654815/125236161-2bcdd100-e2ec-11eb-9f2d-3aeb1d3d592f.png)

**Comment by avdosev** [comment]
Спасибо, я в курсе о проблеме, хабр решил что слать массив нуллов это топ-кек, я исправлю это когда приеду из отпуска на след неделе

Хотя и не понятно чем это заменить массив нуллов с апишки это массив нуллов, наверно, будут теги

**Comment by avdosev** [comment]
Я это починил, но хабр оказался быстрее, чем релиз приложухи)
