### ISSUE TITLE
Проблемы с отображением курсива

### ISSUE THREAD

**Issue by unterumarmung** [avdosev/habr_app#4]
![Пример](https://user-images.githubusercontent.com/39276703/94349543-5220c980-0056-11eb-8440-6a240f4e37b1.jpg)
Ссылка на статью: https://habr.com/ru/company/itelma/blog/518632/

**Comment by avdosev** [comment]
Привет, спасибо. На данный момент о проблеме было известно. Он заключается в том, что некоторые статьи игнорируют тег p из-за чего с их парсингом возникают проблемы. Команда разработчиков (я) работает на этим но в слабом приоритете. Когда проблема будет исправленная я сообщу лично.

**Comment by avdosev** [comment]
Ну в общем чиллер, главный член команды разрабочков или, говоря по простому, я закончил фикс для этого. На данный момент это последний коммит, но он ещё не очень стабильный. В следующем релизе все будет по кайфу.
