### ISSUE TITLE
Добавить возможность редактировать характеристики текста

### ISSUE THREAD

**Issue by unterumarmung** [avdosev/habr_app#6]
1. Шрифт для текста
2. Шрифт для кода (возможно с поддержкой лигатур)
3. Размер шрифта
4. Выравнивание (по левому краю, по правому, по центру, по ширине)

**Comment by avdosev** [comment]
3. готово появится в след релизе

**Comment by avdosev** [comment]
Какие шрифты тебе нужны?

**Comment by avdosev** [comment]
4. готово появится в след релизе

**Comment by avdosev** [comment]
будем считать что пока кастомизации хватит, если будут предложения с конкретным шрифтом, я сделаю
