### ISSUE TITLE
Сделать переключение темы свитчем, а не выпадающим списком

### ISSUE THREAD

**Issue by Sapfir0** [avdosev/habr_app#7]

**Comment by avdosev** [comment]
как ты представляешь свитч на три возможных значения?

**Comment by Sapfir0** [comment]
Если считать, что темы должно быть только 2, то так:
Один свитч переключает на темную тему и обратно.
Второй свитч называется "Использовать системную тему". Если его активировать, то первый свитч блокируется, и  выставляется нужное значение.

**Comment by avdosev** [comment]
Я планировал добавить ещё одну. Но мне нравится то как ты предложил. Сделаю тогда так.

**Comment by avdosev** [comment]
Готово, появится в след релизе
